# Generated by Django 2.1.5 on 2020-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.TextField(max_length=200)),
                ('title', models.TextField(max_length=200)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
