# Generated by Django 2.1.5 on 2020-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
